name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test -- --passWithNoTests

      - name: Rodar build
        run: npm run build
